language: python
python:
- 3.7
- 3.6
- 3.5
- 2.7
env:
- CODECOV_TOKEN=bebb1336-846a-4e5a-a511-b3b6faa0f99b
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: rymurr
  password:
    secure: pk/5Mk2Gh/A1n/TcvGsArxOO8D11cbAfPfATxuRV/gJyhgPiQZ/r6kIgnGOitixp2SJ4G6bxlDBR50/UxZqtJF7AJcOW30E+dakUNNml1JJMoyqV/fa0wvzahv6Ti9Icvs4RUHjPIX8mgQsuGMl3MUrYSz/Eres8OFk3D+Nxma00LnjUZU5xd0SVKoW3ya+QEYbFLqWdF9KDMWzEYsinaEv/g4t9yUbqGclWvqNWGSZtvmGMdajVW5wXdhKrupOvI9pVAnD5ogWpRx16NGV9dk1dCPI1Yx+/cMVkeKJzK30UOLGV13RKr7cz9vZloUVeKWxqd/B165TI2kuI8w2HLgXwxYOk8mKuQg8qHemtk7Jz6cjYzFIg2DxSeSkPpu2HJBIBhYxW/j+5TImsm0ftOjIwxP2VV/+hHkPLNwK+0LyD/VCK2aBwsYblL8a5zWZObtVSP9P43zjXRYfaj4XBtTklGSTGxrCP2LXiSYRrlYtiXPO8ZkJre23gb4JedwfPnHry/8cMB98B6N86slqjkR18nE56LUx7wQsMjaVomLo5g4Pe+ipPfyPcdswHpHFKS3Wa8mstZtjLZappj7bdEJZ1KNU+SEoWzwsikXAMSZDhXaNsNVCJhrU23D6zT71V8Grdgj1zFofhYYv0ocxA8yT3j/kWYbSXwT7jf9XUMrE=
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
    repo: rymurr/dremio_client
