language: python
python:
- 3.7
- 3.6
- 3.5
- 2.7
env:
- CODECOV_TOKEN=bebb1336-846a-4e5a-a511-b3b6faa0f99b
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: rymurr
  password:
    secure: pqqiB6qMfrzc2v9zrIN9KY+FjANU2dY1dzrg9cK1mAcuWw2WjON8tCpRrqufLsVY2QoPshB8nW8g7D1/hpB9jzdOJeSIN/BJTGCYz294D+HVT8fpy33240ims5Lioeay/gHIKYtth5SFEYdizcC8d7TSWmm/TaGICWnRg61O2rwpSQLWnxtZ8SD7rO/ayKIbGdR4grfU9PQTMSXlkRqH+iOpCvNKcJ/URTwKK4KhydvPAYTVSCJ8txcgNmA7oDiMP9NVBeZLAbUeZU513cIdHjRDR+6WfT/P6xRGhHcakR2heDaXSaK3L9pC478IqnfsxZKpR+Mkbg+o8D+NwFXKAuKjxZaE4ZpL+DgEjX2OD7Jp42hmG7GnpN/99JWVlhl7Wagg2Njvvlqka68K1mI8i2euNeEeHXVKFPXVuR+a8ky9GH/Nmnhtycd3i4GmTrMYlG15fudmVAvs2RkKBd9kTUoer+JXIzGAHiX4dY6tt+8ZKovR1Kab20FFF119gtFOOwG3dbkgMlSPjfA1JpgYxn7ZXnOy1clEfO2tRqL7QuYB1w+1ES8+WTtnPpu99XZRvKB/UgjYfsJy+y24j4e8FXccD7kENwe6js/q1JLsxN9pU1ZZEj7NrCKVe5xYHOUf7Gna5bdO5vhmmkUW8KmbJ4nQH7E+Ncp+hDVGVHszDmA=
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
    repo: rymurr/dremio_client
